### ISSUE TITLE
Request GitHub Donate KYC-S154Parker

### ISSUE THREAD

**Issue by parker02311** [DigitalPlatDev/FreeDomain#15728]
Donation amount: $1.00

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

![image](https://github.com/user-attachments/assets/18dcd575-787a-43e7-810e-a6928e7fc426)

**Comment by wukaimei** [comment]
Request GitHub to donate KYC-YOUR_USERNAME
