### ISSUE TITLE
Request GitHub Donate KYC-123

### ISSUE THREAD

**Issue by Daseanle** [DigitalPlatDev/FreeDomain#16123]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by Daseanle** [comment]
<img width="313" alt="身份截图" src="https://github.com/user-attachments/assets/828e8ae2-7e52-4ea9-8929-c92eaedd021e">

**Comment by EdwardLab** [comment]
?
