### ISSUE TITLE
Request GitHub KYC-mayday570

### ISSUE THREAD

**Issue by JettyLee17** [DigitalPlatDev/FreeDomain#16701]
### KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

- [x] The issue title must be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be:  **Request GitHub KYC-example**)
- [x] This is not a new GitHub account; it has existing repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes. 
- [x] Please star this repository, This will let more people know about this project!

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: mayday570
- Reason for Registering the .US.KG Domain Name (Why):just for creating my personal website to share knowledge

**Comment by mbuo123** [comment]
I like a blogger let me recommend, I personally like to build a website, I like to learn the knowledge,

**Comment by JettyLee17** [comment]
> I like a blogger let me recommend, I personally like to build a website, I like to learn the knowledge,

haha，maybe after I done my website,but I just started

**Comment by mbuo123** [comment]
Hāhā, dàgài shì wǒ zuò wán wǎngzhàn zhīhòu, bùguò wǒ cáigāng kāishǐ wǒ de xuéxí
