### ISSUE TITLE
Request GitHub Donate KYC-Addisonbig

### ISSUE THREAD

**Issue by goherok** [DigitalPlatDev/FreeDomain#16796]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by EdwardLab** [comment]
Please attach screenshot of your donation thank you

**Comment by goherok** [comment]
Hello sir, this account was registered using an outlook email address. Is this a whitelist? Email: GOHeroku@outlook.com, first time to register, I don’t understand

**Comment by EdwardLab** [comment]
Please resubmit "Request GitHub KYC" not "Request GitHub Donate KYC-" Template please
