### ISSUE TITLE
Request GitHub Donate KYC-lzhan

### ISSUE THREAD

**Issue by lzhan0121** [DigitalPlatDev/FreeDomain#16855]
![屏幕截图 2024-11-01 215613](https://github.com/user-attachments/assets/07ef5bfb-387c-490c-b896-6ca45444bdbe)
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by lzhan0121** [comment]
Hello, I logged into my account and it shows that it is still waiting for KYC verification. Is there something wrong?

**Comment by stdff** [comment]
好用
