### ISSUE TITLE
申请域名

### ISSUE THREAD

**Issue by yeyugehfuy** [DigitalPlatDev/FreeDomain#16975]
### KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

- [ ] The issue title must be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be:  **Request GitHub KYC-example**)
- [ ] This is not a new GitHub account; it has existing repositories and stars.
- [ ] This is my first US.KG NIC Panel account.
- [ ] I promise not to use the domain name for criminal or abusive purposes. 
- [ ] Please star this repository, This will let more people know about this project!

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:
![2fbeb9dba3544316439a510069648c7](https://github.com/user-attachments/assets/7dd3ba40-44dd-4447-bfb9-d918ddda86b8)
![07a85e81df7d23a2487b482825c0277](https://github.com/user-attachments/assets/82e1488c-a168-4625-a8cc-1815aa8809a4)

- Username: yeyuxinyue.us.kg/
- Reason for Registering the .US.KG Domain Name (Why):
- Because I want a domain name that belongs to me to bind my own notifications

**Comment by GLASS20** [comment]
your title should be: Request GitHub KYC-example

**Comment by eoboyweb** [comment]
GASS20, he payed a dollar and showed it. Therefore it should be Request GitHub Donate KYC=example
