### ISSUE TITLE
Request GitHub Donate KYC-alex..6268

### ISSUE THREAD

**Issue by ckj6666** [DigitalPlatDev/FreeDomain#20420]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by ckj6666** [comment]
Thanks. Have a good day

**Comment by EdwardLab** [comment]
Please attach screenshot of your donation thank you
