### ISSUE TITLE
Request GitHub Donate KYC-yiwanchaofna

### ISSUE THREAD

**Issue by YIwanchaofan** [DigitalPlatDev/FreeDomain#24205]
Donation amount: US $1

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!
![1731690439711](https://github.com/user-attachments/assets/5174d9f6-03ec-4078-8641-e064252dca4e)

**Comment by TgDaosheng** [comment]
We discovered during the review of your GitHub account that you used a "$1 donation amount" to bypass administrator review, and you have been identified as an insecure KYC. Your request will never be approved, and the email address you registered for the account will be permanently blocked.
