### ISSUE TITLE
Request GitHub Donate KYC-liangxiaoya

### ISSUE THREAD

**Issue by xiaoya219** [DigitalPlatDev/FreeDomain#24979]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by xiaoya219** [comment]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4439424575423447336 skey=@crypt_8666f5d6_0a1e8885bd4e775d54314f8b444685ec mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/4658f06f-b853-40cd-b525-5aa2cb750b43)

**Comment by yzhpxd** [comment]
我去，一刀还要验证？？
