### ISSUE TITLE
Request GitHub KYC-AORUIPING

### ISSUE THREAD

**Issue by AORUIPING21** [DigitalPlatDev/FreeDomain#27896]
### KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

- [x] The issue title must be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be:  **Request GitHub KYC-example**)
- [x] This is not a new GitHub account; it has existing repositories and stars.
- [x] This is my first US.KG NIC Panel account.
- [x] I promise not to use the domain name for criminal or abusive purposes. 
- [x] Please star this repository, This will let more people know about this project!

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: AORUIPING
- Reason for Registering the .US.KG Domain Name (Why):Study and build a website

**Comment by laorui** [comment]
> ### laorui_68@outlook.com
> 请确保您的GitHub帐户满足以下要求(全部要求)：
> 
> * [+] 问题标题必须为：请求GitHub KYC-您的US.KG面板注册用户名。这可确保我们的自动脚本可以检测您的注册用户名。(例如，您的标题应为：**请求GitHub KYC-示例**)
> * [+] 这不是一个新的GitHub帐户；它有现有的存储库和星。
> * [+] 这是我的第一个US.KG NIC面板帐户。
> * [+] 我保证不将域名用于犯罪或滥用目的。
> * [+] 请启动这个资源库，这将让更多的人知道这个项目！
> 
> **您的帐户详细信息(US.KG NIC面板)：laorui_68@outlook.com**
> 
> 请填写以下信息；否则，您的请求将不会得到处理：
> 
> * 用户名：laorui788
> * 注册.US.KG域名的原因(为什么)：学习和建立网站

**Comment by laorui** [comment]
互相理解，互相关注。

**Comment by laorui** [comment]
互相理解，互相关注。
