### ISSUE TITLE
Request GitHub Donate KYC-Booomeii

### ISSUE THREAD

**Issue by Booome** [DigitalPlatDev/FreeDomain#31134]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

![屏幕截图 2024-11-29 151658](https://github.com/user-attachments/assets/d9c5b5c3-8616-404e-8f2b-9e6303765444)

**Comment by TgDaosheng** [comment]
We discovered during the review of your GitHub account that you used a "$1 donation amount" to bypass administrator review, and you have been identified as an insecure KYC. Your request will never be approved, and the email address you registered for the account will be permanently blocked.

**Comment by Booome** [comment]
> We discovered during the review of your GitHub account that you used a "$1 donation amount" to bypass administrator review, and you have been identified as an insecure KYC. Your request will never be approved, and the email address you registered for the account will be permanently blocked.

@EdwardLab I am not sure, Is this guy a andmin of your group? I truely made two PRs, because at first I donated $1 in the hope that my PR can pass quickly, but it blocked over a hour, and I found the free one passes much quicker, so I make a another PR.
 I don't quite understand what the problem is.
