### ISSUE TITLE
Request GitHub Donate KYC-xinxian

### ISSUE THREAD

**Issue by 112321412** [DigitalPlatDev/FreeDomain#33631]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by laorui** [comment]
Request GitHub Donate KYC-laorui788

________________________________
发件人: 112321412 ***@***.***>
发送时间: 2024年12月2日 下午 08:29
收件人: DigitalPlatDev/FreeDomain ***@***.***>
抄送: Subscribed ***@***.***>
主题: [DigitalPlatDev/FreeDomain] Request GitHub Donate KYC-xinxian (Issue #33631)


Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

―
