### ISSUE TITLE
Request GitHub Donate KYC-北巷南街啊

### ISSUE THREAD

**Issue by beixiangxxw** [DigitalPlatDev/FreeDomain#34281]
![Uploading QQ20241124-140007.png…]()
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by EdwardLab** [comment]
Image cannot open, resubmit thank you
