### ISSUE TITLE
Request GitHub KYC-xyradinka

### ISSUE THREAD

**Issue by clyfly** [DigitalPlatDev/FreeDomain#49244]
- Username:  xyradinka
- Reason for Registering the .US.KG Domain Name (Why): I need a domain for my google drive index site, I run a service on telegram whose main function is to mirror user files to google drive (I make sure no nfsw on it) please accept my request, thank you

**Comment by EdwardLab** [comment]
Approved, you can now sign in to US.KG Panel and get a new domain!!! :) (WARNING: Bulk account registration, use for criminal activities, or any violation of the Acceptable Use Policy is strictly prohibited. If detected, we will immediately suspend your domain resolution and report the issue to cybersecurity firms/organizations or relevant government authorities.)
