### ISSUE TITLE
Request GitHub Donate KYC-daoxin

### ISSUE THREAD

**Issue by liuhangbiao** [DigitalPlatDev/FreeDomain#51341]
Donation amount:

Make sure the title format is "Request GitHub Donate KYC-YOUR_USERNAME", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the GitHub Donate KYC issue template to include a field for donation amount and instructions for attaching a donation receipt screenshot.

You can review changes in this commit: https://github.com/kkpo4553/DigitalPlatDev-FreeDomain-51341/commit/8a6355cae9f5c7d70f0a753e58c4b29861b7c0e3.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
