### ISSUE TITLE
跑路了！！！

### ISSUE THREAD

**Issue by so1910** [DigitalPlatDev/FreeDomain#73488]

**Comment by LiuYanHao789** [comment]
6

**Comment by Wuchieh** [comment]
人家又沒收錢 談何跑路?
況且對方有發 email 通知情況

**Comment by yoyo115956** [comment]
check:
https://github.com/DigitalPlatDev/FreeDomain/blob/main/documents/announcement.md
please

**Comment by StuartYang** [comment]
恢复了，我的可以正常访问了
