### ISSUE TITLE
Request GitHub KYC-Quandell

### ISSUE THREAD

**Issue by samsam-coder** [DigitalPlatDev/FreeDomain#74036]
### KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

- [ ] The issue title **must** be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be:  **Request GitHub KYC-example**)
- [ ] This is not a new GitHub account; it has existing repositories and stars. (New registered GitHub accounts are not accepted)
- [ ] This is my first DigitalPlat FreeDomain account.
- [ ] I promise not to use the domain name for criminal or abusive purposes. 

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: 
- Reason for Registering the .US.KG Domain Name (Why):

**Comment by laorui** [comment]
> ### KYC Using Your GitHub Account:laorui_68@outlook.com 
> KYC使用您的GitHub帐户
> 使用您的 GitHub 帐户进行 KYC
> KYC使用您的GitHub帐户
> Please make sure your GitHub account meets the following requirements (all are required):请确保您的GitHub帐户符合以下要求（全部为必填项）：请确保您的 GitHub 帐户满足以下要求（全部为必填项）：请确保您的GitHub帐户符合以下要求（全部是必需的）：
> 
> * [ Request GitHub KYC-laorui788]  The issue title **must** be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be:  **Request GitHub KYC-example**)问题标题**必须**是：请求GitHub KYC -您在US.KG Panel注册的用户名。这可以确保我们的自动脚本可以检测到您注册的用户名。(For例如，您的标题应该是：**请求GitHub KYC-示例**）问题标题**必须**为：Request GitHub KYC - Your US。KG Panel 注册用户名。这可确保我们的自动脚本可以检测到您注册的用户名。（例如，您的标题应为：**Request GitHub KYC-example**）问题的标题必须是：请求GitHub KYC -你的美国。KG面板注册用户名。这确保我们的自动脚本可以检测到您的注册用户名。（例如，你的标题应该是：请求GitHub KYC-example）问题的标题必须是：请求GitHub KYC -你的美国。 KG面板注册用户名。 这确保我们的自动脚本可以检测到您的注册用户名。 （例如，你的标题应该是：请求GitHub KYC-example）
> * [ +]  This is not a new GitHub account; it has existing repositories and stars. (New registered GitHub accounts are not accepted)这不是一个新的GitHub帐户;它有现有的存储库和星星。(New不接受注册的GitHub帐户）这不是一个新的 GitHub 帐户;它具有现有的存储库和星标。（不接受新注册的 GitHub 帐户）这不是一个新的GitHub帐户；它有现有的存储库和星星。（不接受新注册的GitHub帐户）
> * [ +]  This is my first DigitalPlat FreeDomain account.这是我的第一个DigitalPlat FreeDomain帐户。这是我的第一个 DigitalPlat FreeDomain 帐户。这是我的第一个数字平台自由域账户。
> * [ +]  I promise not to use the domain name for criminal or abusive purposes.我保证不会将域名用于犯罪或滥用目的。我承诺不会将域名用于犯罪或滥用目的。我保证不将域名用于犯罪或滥用目的。
> 
> **Your Account Details (US.KG NIC Panel):您的帐户详细信息（US.KG NIC Panel）：您的帐户详细信息 （US.KG 网卡面板）：您的帐户详情(美国)KG网卡面板):laorui_68@outlook.com **
> 
> Please fill out the following information; otherwise, your request will not be processed:请填写以下信息;否则，您的请求将不被处理：请填写以下信息;否则，您的请求将不会被处理：请填写以下资料;否则，你的要求将不获处理:
> 
> * Username:   用户名:用户名：laorui788
> * Reason for Registering the .US.KG Domain Name (Why):注册.US.KG域名的原因（为什么）：注册 的原因。我们。KG 域名（为什么）：注册. us域名的原因。KG域名（为什么）：注册. us域名的原因。 KG域名（为什么）：Learn  and  build websites
