### ISSUE TITLE
Request GitHub Donate KYC-KJRogers2424

### ISSUE THREAD

**Issue by KJRogers2424** [DigitalPlatDev/FreeDomain#74190]
Donation amount: 1

Make sure the title format is "Request GitHub Donate KYC-KJRogers2424", After that, you can submit your request! You may also attach a screenshot of the donation receipt, thank you!

**Comment by joey-sam** [comment]
捐款金额： 1

确保标题格式为“Request GitHub Donate KYC-joey-sam”，之后即可提交请求！您也可以附上捐款收据的截图，谢谢！

**Comment by KJRogers2424** [comment]
Do I get a domain? Or
